Olá! Este é o desafio relativo ao Primeiro Contato com o Google Colab.

Aqui você poderá pôr em prática os seus conhecimentos recém adquiridos. Use as células abaixo para realizar as tarefas propostas.

# Tarefa 1

"monte o seu drive"

In [ ]:
from google.colab import drive
drive.mount("/content/drive/");
pathModulo1 = "/content/drive/MyDrive/Colab Notebooks/USP/hype/Dojo_de_Machine_Learning/Módulo 1"

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

# Tarefa 2

Procure um Dataset que voce tenha interesse no Kaggle. Se tiver dificuldade escolha um dos abaixo:

- https://www.kaggle.com/datasets/alphiree/cardiovascular-diseases-risk-prediction-dataset
- https://www.kaggle.com/datasets/arnavsmayan/netflix-userbase-dataset
- https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

# Tarefa 3

importe o seu Dataset

In [41]:
import pandas as pd
#drivePathArq = "/content/drive/MyDrive/Colab Notebooks/USP/hype/Dojo_de_Machine_Learning/Módulo 1/atlas.csv"
#dataFrame = pd.read_csv(drivePathArq)
drivePathArq = "/content/drive/MyDrive/Colab Notebooks/USP/hype/Dojo_de_Machine_Learning/Módulo 1/world-data-2023.csv"
dataFrame = pd.read_csv(drivePathArq)

# Tarefa 4

obtenha algumas medidas desse Dataframe

In [ ]:
rowAndColumnCount = dataFrame.shape
for test in rowAndColumnCount:
  print(test)
dataFrame.describe()

195
35

,Birth Rate,Calling Code,Fertility Rate,Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Latitude,Longitude
count,189.000000,194.000000,188.000000,189.000000,187.000000,181.000000,188.000000,194.000000,194.000000
mean,20.214974,360.546392,2.698138,21.332804,72.279679,160.392265,1.839840,19.092351,20.232434
std,9.945774,323.236419,1.282267,19.548058,7.483661,233.502024,1.684261,23.961779,66.716110
min,5.900000,1.000000,0.980000,1.400000,52.800000,2.000000,0.010000,-40.900557,-175.198242
25%,11.300000,82.500000,1.705000,6.000000,67.000000,13.000000,0.332500,4.544175,-7.941496
50%,17.950000,255.500000,2.245000,14.000000,73.200000,53.000000,1.460000,17.273849,20.972652
75%,28.750000,506.750000,3.597500,32.700000,77.500000,186.000000,2.935000,40.124603,48.281523
max,46.080000,1876.000000,6.910000,84.500000,85.400000,1150.000000,8.420000,64.963051,178.065032

In [ ]:
dataFrame.head()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"6,52,230","3,23,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"3,80,41,754",48.90%,9.30%,71.40%,11.12%,"97,97,273",33.939110,67.709953
1,Albania,105,AL,43.10%,"28,748","9,000",11.78,355.0,Tirana,"4,536",...,56.90%,1.20,"28,54,191",55.70%,18.60%,36.60%,12.33%,"17,47,593",41.153332,20.168331
2,Algeria,18,DZ,17.40%,"23,81,741","3,17,000",24.28,213.0,Algiers,"1,50,006",...,28.10%,1.72,"4,30,53,054",41.20%,37.20%,66.10%,11.70%,"3,15,10,100",28.033886,1.659626
3,Andorra,164,AD,40.00%,468,NaN,7.20,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",NaN,NaN,NaN,NaN,"67,873",42.506285,1.521801
4,Angola,26,AO,47.50%,"12,46,700","1,17,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"3,18,25,295",77.50%,9.20%,49.10%,6.89%,"2,10,61,025",-11.202692,17.873887

In [ ]:
dataFrame.tail()

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
190,Venezuela,32,VE,24.50%,"9,12,050","3,43,000",17.88,58.0,Caracas,"1,64,175",...,45.80%,1.92,"2,85,15,829",59.70%,NaN,73.30%,8.80%,"2,51,62,368",6.423750,-66.589730
191,Vietnam,314,VN,39.30%,"3,31,210","5,22,000",16.75,84.0,Hanoi,"1,92,668",...,43.50%,0.82,"9,64,62,106",77.40%,19.10%,37.60%,2.01%,"3,53,32,140",14.058324,108.277199
192,Yemen,56,YE,44.60%,"5,27,968","40,000",30.45,967.0,Sanaa,"10,609",...,81.00%,0.31,"2,91,61,922",38.00%,NaN,26.60%,12.91%,"1,08,69,523",15.552727,48.516388
193,Zambia,25,ZM,32.10%,"7,52,618","16,000",36.19,260.0,Lusaka,"5,141",...,27.50%,1.19,"1,78,61,030",74.60%,16.20%,15.60%,11.43%,"78,71,713",-13.133897,27.849332
194,Zimbabwe,38,ZW,41.90%,"3,90,757","51,000",30.68,263.0,Harare,"10,983",...,25.80%,0.21,"1,46,45,468",83.10%,20.70%,31.60%,4.95%,"47,17,305",-19.015438,29.154857

In [ ]:
dataFrame.sample(5)

,ano,codmun6,uf,codmun7,município,espvida,fectot,mort1,mort5,razdep,...,pia1517,pia18m,pop,popt,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r
14483,2010,350770,35,3507704,BRAÚNA,74.77,1.96,15.10,17.47,47.81,...,237.0,3777.0,4997,4997,0.475,0.785,0.737,0.664,0.830,0.725
1639,1991,261570,26,2615706,TRIUNFO,65.51,3.25,47.64,63.15,84.89,...,NaN,NaN,15733,15618,0.171,0.232,0.404,0.210,0.675,0.466
13929,2010,314770,31,3147709,Passa Tempo,73.46,1.44,17.80,20.71,43.73,...,460.0,6196.0,8144,7957,0.368,0.755,0.687,0.594,0.808,0.676
7567,2000,291480,29,2914802,ITABUNA,68.95,2.21,29.84,38.32,52.67,...,14041.0,125766.0,192736,189802,0.392,0.436,0.581,0.421,0.733,0.636
13361,2010,293300,29,2933000,VALENTE,68.75,1.73,31.40,33.83,45.25,...,1316.0,17529.0,24545,24318,0.413,0.666,0.637,0.568,0.729,0.623

# Tarefa 5

examine o Dataframe, trate valores nulos e linhas duplicadas.

In [ ]:
dataFrame.isnull().sum()

Country                                       0
Density\n(P/Km2)                              0
Abbreviation                                  7
Agricultural Land( %)                         7
Land Area(Km2)                                1
Armed Forces size                            24
Birth Rate                                    6
Calling Code                                  1
Capital/Major City                            3
Co2-Emissions                                 7
CPI                                          17
CPI Change (%)                               16
Currency-Code                                15
Fertility Rate                                7
Forested Area (%)                             7
Gasoline Price                               20
GDP                                           2
Gross primary education enrollment (%)        7
Gross tertiary education enrollment (%)      12
Infant mortality                              6
Largest city                                  6
Life expectancy                               8
Maternal mortality ratio                     14
Minimum wage                                 45
Official language                             5
Out of pocket health expenditure              7
Physicians per thousand                       7
Population                                    1
Population: Labor force participation (%)    19
Tax revenue (%)                              26
Total tax rate                               12
Unemployment rate                            19
Urban_population                              5
Latitude                                      1
Longitude                                     1
dtype: int64

In [45]:
#Função para calcular mediana de strings
def list_function(column):
  nums = list()
  for number in dataFrame[column]:
    if(str(number)[0] == "$"):
      nums.append(str(number)[1:])
    else:
      nums.append(str(number)[:-1])
  return nums


for column in dataFrame.columns:
  pos = 0
  sampleColumn =  dataFrame[column].sample(5).to_list()
  for key, sample in enumerate(sampleColumn):
    if(str(sample) != "nan"):
      pos = key
      break
  try:
    strSample = str(sampleColumn[pos])
    if("%" not in strSample and "$" not in strSample  and not strSample[0].isnumeric()):
      dataFrame[column] = dataFrame[column].fillna("NA")
    else:
      dataFrame[column] = dataFrame[column].fillna(dataFrame[column].mean)
  except:
    text = f"${list_function(column).mean}"
    if(sampleColumn[pos][0]!="$"):
      text = f"{list_function(column).mean}%"
    dataFrame[column] = dataFrame[column].fillna(text)

In [ ]:
dataFrame.duplicated().sum()

np.int64(0)

# Tarefa 6

Extraia algumas colunas (Series) do Dataframe

In [22]:
serie = dataFrame[["Country", "Abbreviation", "Co2-Emissions"]]
serieOnce = dataFrame["Population"]
serieOnce

0      3,80,41,754
1        28,54,191
2      4,30,53,054
3           77,142
4      3,18,25,295
          ...
190    2,85,15,829
191    9,64,62,106
192    2,91,61,922
193    1,78,61,030
194    1,46,45,468
Name: Population, Length: 195, dtype: object

# Tarefa 7

Obtenha algumas medidas dessas colunas (Series)

In [38]:
dfGroup = dataFrame[["Country", "Co2-Emissions","Population"]]
dfGroup = dfGroup.groupby("Country").mean()
print(dfGroup)

TypeError: agg function failed [how->mean,dtype->object]

# Tarefa 8

Extraia linhas de um dataset baseado no valor de uma variável específica

In [46]:
dataFrame.iloc[[0,3,6]]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"6,52,230","3,23,000",32.49,93.0,Kabul,"8,672",...,78.40%,0.28,"3,80,41,754",48.90%,9.30%,71.40%,11.12%,"97,97,273",33.93911,67.709953
3,Andorra,164,AD,40.00%,468,"<bound method Series.mean of 0 3,23,000\n...",7.2,376.0,Andorra la Vella,469,...,36.40%,3.33,"77,142",<bound method Series.mean of 0 48.90%\n1 ...,<bound method Series.mean of 0 9.30%\n1 ...,<bound method Series.mean of 0 71.40%\n1 ...,<bound method Series.mean of 0 11.12%\n1 ...,"67,873",42.506285,1.521801
6,Argentina,17,AR,54.30%,"27,80,400","1,05,000",17.02,54.0,Buenos Aires,"2,01,348",...,17.60%,3.96,"4,49,38,712",61.30%,10.10%,106.30%,9.79%,"4,13,39,571",-38.416097,-63.616672

# Tarefa 8

Realize um agrupamento de uma coluna com a função groupby()